---
# Template configuration files for cron

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ cron_templates_copy }}"
  when: cron_copy_templates
